on: [push]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.ACTIONS_TOKEN }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'mpwsh',
            repo: 'remote-repo-test',
            workflow_id: 'main.yaml',
            ref: 'main'
          })
