on: [push]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: Triggering deployment update in remote repository
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.ACTIONS_TOKEN }}
        env:
          BRANCH: ${{GITHUB_REF##*/}}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'mpwsh',
            repo: 'remote-repo-test',
            workflow_id: process.env.BRANCH + '.yaml',
            ref: process.env.BRANCH
          })
