on: [push]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Triggering deployment update in remote repository
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.ACTIONS_TOKEN }}
        script: |
          console.log(process.env.GITHUB_HEAD_REF);
          await github.rest.actions.createWorkflowDispatch({
            owner: 'mpwsh',
            repo: 'remote-repo-test',
            workflow_id: process.env.GITHUB_HEAD_REF + '.yaml',
            ref: process.env.GITHUB_HEAD_REF
          })
